sudo: required
services:
- docker
before_install:
- docker build -t opusidea/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true opusidea/docker-react npm run test
deploy:
  provider: heroku
  api_key:
    secure: L+ODompTSVd8P3EDGv2FDF3mcNVq+LCRZyJp/PQ5zdeWiZxlvPltm+QrFnxZ68W6rqfpb5A/R+pZtjPqgMW/91NAPVBV7HLuHjczPpoFhctD14X9IapLpehWal+dDy2J68kauVD8B7RPQmDMVlZeVDo5d22jbwatkRiHYj8oivPQGsBrBSokg+gwyTfScUbx7T81LCRzXQ7Zts7hYaZnSJHT6t+2sA9Oun9xR1d2YKIGZAc5rP44GSUZhCmW2FBeWqJqX1iFeAOnhGPUeFVXOpENWNjUMQJIZ+RlWKGB6QCsK41iT16sWDcp5Hf7eeuzvZiJ6WITXth8p4VqMg7O0TArh93NyoJ3+sGgjD9x/Py+iPZVwMI0b6zWFM+M4zkFKUfeaclIj3xlxdXss/K1uOwB2LO25qmuub1X+NZVZTB25m2RohQILgc/YYN84X6rtxf093h9YkLjYqaPpGfzusyhlnLFDb1/hXDEPNkUHY31FfeXwwOnphOwYqBqi1iU+Xmj3ii/MJDTlYIWA99j2CAleQm/0WucHn3nnhNaiNnS5fmKV1mRRcgS6YaVWeJ4CXqYdNszclEGJpUSWvojaqhwVkiunyo/jymKmxEe+muEjYC1D6Hq2tzHdiioxWX3ZBDR9FI8Y+NAmN0bFUQCNpC7D4jr8KOLZGx2zuCgl5s=
  app: docker--react
  on:
    repo: cdufour/docker-react
