sudo: required
services:
- docker
before_install:
- docker build -t opusidea/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true opusidea/docker-react npm run test
deploy:
  provider: heroku
  api_key:
    secure: mf1gY35v0NYijHOWvvKA9ogt2y7nVm1zeGgzWIFeRD79pQaE/Pk17gb2XZUNWyYgjaLgz8/LhzarGsrwxNSSsWblHUFmChglrOvnxpvFPmgxX3jYvIeeYwFmy8eaiD2ILVMa3aduTaJZyRxpKUk/Ippa63aLFSTueOgJ9akyy6FPz3xj6qQRKyH8XizoJT3AfdPGvoL2lcMkNLm1HhV3rrEH38tA+W6oO7qRLigmzWftKws43q06bYPGypVECVA6WA7W535Ua2zbmmjEmNPX/8d/ASiS3YWa+v0Kk4paM/KTu9SGkkU12sqTdc7+STDf3/qf9yvXDO79YJw2bS0HASa3nsIfDMPN0Th72UIfkPy27p8niH2MFTyYW21CB5KIB1zIWzTlYgNQ1Vw9+iJ0Gu3h6iybuSBT3gzoFCDQVMIXZQgHPyx67IAolyXAKsGlwyXVbutCvco0BVeeglf+2Ds3o6KWCtCcMOo5yFIqEMDcZy61sRmYM6ZHmlKtjqgxIcaI18rQgQ7x38CQweq1sVbLRSJUR6UCRBt4cUcxwq1eIWBxVPX+UIwuQEKV+OpgZb6FAAWNs69nSi/TYfNvpRQ3dBRhSVljQ2o/A8zs96R6ItRtkR2HXY0SxsUgH+mU04HINAJ88H4o1QMUDSApq++LGjq1MsfKr+Jt8sc5ue4=
